// Mocks generated by Mockito 5.4.6 from annotations
// in personal_pim/test/pages/home_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:personal_pim/models/contact.dart' as _i4;
import 'package:personal_pim/models/todo.dart' as _i5;
import 'package:personal_pim/services/firestore_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i2.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addContact(_i4.Contact? contact) =>
      (super.noSuchMethod(
            Invocation.method(#addContact, [contact]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addTodo(_i5.Todo? todo) =>
      (super.noSuchMethod(
            Invocation.method(#addTodo, [todo]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTodo(_i5.Todo? todo) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodo, [todo]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTodo(String? todoId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodo, [todoId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i5.Todo>> getTodosStream() =>
      (super.noSuchMethod(
            Invocation.method(#getTodosStream, []),
            returnValue: _i3.Stream<List<_i5.Todo>>.empty(),
          )
          as _i3.Stream<List<_i5.Todo>>);

  @override
  _i3.Future<void> updateContact(_i4.Contact? contact) =>
      (super.noSuchMethod(
            Invocation.method(#updateContact, [contact]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> renameGroupGlobal(String? oldName, String? newName) =>
      (super.noSuchMethod(
            Invocation.method(#renameGroupGlobal, [oldName, newName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteGroupGlobal(String? groupName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGroupGlobal, [groupName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateAllContactsOrder(List<_i4.Contact>? contacts) =>
      (super.noSuchMethod(
            Invocation.method(#updateAllContactsOrder, [contacts]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteContact(String? contactId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteContact, [contactId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getFieldUsageCount(String? fieldKey) =>
      (super.noSuchMethod(
            Invocation.method(#getFieldUsageCount, [fieldKey]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> deleteFieldGlobal(String? fieldKey) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFieldGlobal, [fieldKey]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Contact>> getAllContacts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllContacts, []),
            returnValue: _i3.Future<List<_i4.Contact>>.value(<_i4.Contact>[]),
          )
          as _i3.Future<List<_i4.Contact>>);

  @override
  _i3.Future<_i4.Contact?> getContact(String? contactId) =>
      (super.noSuchMethod(
            Invocation.method(#getContact, [contactId]),
            returnValue: _i3.Future<_i4.Contact?>.value(),
          )
          as _i3.Future<_i4.Contact?>);

  @override
  _i3.Future<void> importContacts(List<_i4.Contact>? contacts) =>
      (super.noSuchMethod(
            Invocation.method(#importContacts, [contacts]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.Contact>> getContactsStream() =>
      (super.noSuchMethod(
            Invocation.method(#getContactsStream, []),
            returnValue: _i3.Stream<List<_i4.Contact>>.empty(),
          )
          as _i3.Stream<List<_i4.Contact>>);

  @override
  _i3.Future<void> initializeUserDatabase(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#initializeUserDatabase, [languageCode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
