// Mocks generated by Mockito 5.4.6 from annotations
// in personal_pim/test/services/gemini_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:google_generative_ai/google_generative_ai.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:personal_pim/services/gemini_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGeminiResponse_0 extends _i1.SmartFake
    implements _i2.GeminiResponse {
  _FakeGeminiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GeminiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiClient extends _i1.Mock implements _i2.GeminiClient {
  MockGeminiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.GeminiResponse> generateContent(
    Iterable<_i4.Content>? content,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateContent, [content]),
            returnValue: _i3.Future<_i2.GeminiResponse>.value(
              _FakeGeminiResponse_0(
                this,
                Invocation.method(#generateContent, [content]),
              ),
            ),
          )
          as _i3.Future<_i2.GeminiResponse>);
}

/// A class which mocks [GeminiResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiResponse extends _i1.Mock implements _i2.GeminiResponse {
  MockGeminiResponse() {
    _i1.throwOnMissingStub(this);
  }
}
