// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAihfwiTMzlf3c9uuchfI-3Kw0w1Ib6fRI',
    appId: '1:151482638658:web:d43c330048415ebb6968db',
    messagingSenderId: '151482638658',
    projectId: 'personal-pim',
    authDomain: 'personal-pim.firebaseapp.com',
    storageBucket: 'personal-pim.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk4N0qLwe5qCTW7Dz-uFha1QwieMsXXMo',
    appId: '1:151482638658:android:728cb00d2072c79a6968db',
    messagingSenderId: '151482638658',
    projectId: 'personal-pim',
    storageBucket: 'personal-pim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpr42HWWIXjGZSWxImGy8sD4GnF9jeOJk',
    appId: '1:151482638658:ios:420029f39c337e106968db',
    messagingSenderId: '151482638658',
    projectId: 'personal-pim',
    storageBucket: 'personal-pim.firebasestorage.app',
    androidClientId: '151482638658-ai1pu7p249vuntfl2bpuaa5sbitf99eu.apps.googleusercontent.com',
    iosClientId: '151482638658-5febh0ie5dl8fa7mm7s3msv82k8egpbg.apps.googleusercontent.com',
    iosBundleId: 'com.ladikov.personalPim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpr42HWWIXjGZSWxImGy8sD4GnF9jeOJk',
    appId: '1:151482638658:ios:420029f39c337e106968db',
    messagingSenderId: '151482638658',
    projectId: 'personal-pim',
    storageBucket: 'personal-pim.firebasestorage.app',
    androidClientId: '151482638658-ai1pu7p249vuntfl2bpuaa5sbitf99eu.apps.googleusercontent.com',
    iosClientId: '151482638658-5febh0ie5dl8fa7mm7s3msv82k8egpbg.apps.googleusercontent.com',
    iosBundleId: 'com.ladikov.personalPim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAihfwiTMzlf3c9uuchfI-3Kw0w1Ib6fRI',
    appId: '1:151482638658:web:d43c330048415ebb6968db',
    messagingSenderId: '151482638658',
    projectId: 'personal-pim',
    authDomain: 'personal-pim.firebaseapp.com',
    storageBucket: 'personal-pim.firebasestorage.app',
  );

}